### ISSUE TITLE
TotalSegmentator.exe': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Hurmean** [lassoan/SlicerTotalSegmentator#49]
When I use TotalSegmentator, I encounter the following issues
![1700839166689](https://github.com/lassoan/SlicerTotalSegmentator/assets/12394658/0d9a3ca6-12f7-416c-a8c1-8fb1f2bf6767)

**Comment by lassoan** [comment]
Does the file exist? Does the folder exist?

You may need to force reinstall TotalSegmentator.

**Comment by Hurmean** [comment]
TotalSegmentator.exe not exist

**Comment by Hurmean** [comment]
> Does the file exist? Does the folder exist?
> 
> You may need to force reinstall TotalSegmentator.
TotalSegmentator.exe not exist, i fore reinstall several times, but it don't work

**Comment by lassoan** [comment]
Do you use a third-party antivirus software?

**Comment by Hurmean** [comment]
@lassoan  no third-party antivirus software

**Comment by lassoan** [comment]
I've managed to reproduce the issue. It seems that a quick fix that we added on request by another user (https://github.com/lassoan/SlicerTotalSegmentator/issues/48) caused this problem. I've fixed it in https://github.com/lassoan/SlicerTotalSegmentator/issues/49 now, but since there are no more extension updates for Slicer-4.4, you would need to switch to Slicer-5.6 or manually apply the [change](https://github.com/lassoan/SlicerTotalSegmentator/commit/1f486555d5cf5332e6f5e3eab6821eb43a477d22) on your computer.
