### ISSUE TITLE
Add v2 class maps

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerTotalSegmentator#9]
More tasks were added in [add v2 class maps](https://github.com/wasserth/TotalSegmentator/commit/390a5b7f55035b8bcc5f682c3a088f720a9a2ef5) as demostrated here: https://github.com/wasserth/TotalSegmentator/blob/390a5b7f55035b8bcc5f682c3a088f720a9a2ef5/totalsegmentator/map_to_binary.py#L108-L319

Should I try to make necessary changes on a pull-request?

**Comment by lassoan** [comment]
v2 class maps are not ready yet (confirmed by Jakob).
I've already started to add terminology for the new segments but when it turned out that they are not available yet then I stopped. I've already added the new segmentation tasks, though.

It would be nice if you could keep an eye on the TotalSegmentator repository and when the additional segments are actually available then finish adding the new segments to the repository.

**Comment by mauigna06** [comment]
> It would be nice if you could keep an eye on the TotalSegmentator repository and when the additional segments are actually available then finish adding the new segments to the repository.

I'll do

**Comment by marcus-wirtz-snkeos** [comment]
Ok, just saw the new PR #32, never mind & thanks for the great job! :-)

**Comment by lassoan** [comment]
Transition to v2 is almost completed - see https://github.com/lassoan/SlicerTotalSegmentator/pull/38
